#!/bin/bash

set -e

if [[ -n "${DEBUG_MODE}" ]]; then
  set -x
fi

function usage() {
  echo -n \
    "Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
  GIT_COMMIT="${GIT_COMMIT:0:7}"
else
  GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  if [ "${1:-}" = "--help" ]; then
    usage
  else
    mkdir -p ./build/libs
    rm -f ./build/libs/*.jar

    USER=ci USER_ID=$(id -u) GROUP_ID=$(id -g) GIT_COMMIT="${GIT_COMMIT}" docker-compose -f docker-compose.yml \
      run --rm \
      --user "$(id -u):$(id -g)" \
      cibuild
  fi
fi
