#!/bin/bash

set -e

if [[ -n "${DEBUG_MODE}" ]]; then
  set -x
fi

function usage() {
  echo -n \
    "Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  if [ "${1:-}" = "--help" ]; then
    usage
  else
    CI="${CI:-}" docker-compose -f docker-compose.ci.yml \
      run --rm cibuild
  fi
fi
