#!/bin/bash

set -e

if [[ -n "${FORGEHAX_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Provision bare minimum required to compile a minecraft mod.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else        
        mkdir -p .gradle
        docker-compose \
            -f docker-compose.ci.yml \
            run --rm \
            forgehax clean --stacktrace

        docker-compose \
            -f docker-compose.ci.yml \
            run --rm \
            forgehax setupDecompWorkspace --stacktrace
    fi
fi
